- type: job
  id: ADTSeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobADTSeniorResearcher
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 60h
  weight: 9
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience
    belt: ClothingBeltUtilityFilled
    pocket1: AnomalyLocatorEmpty
  storage:
    back:
    - ADTHumanCubeWrapped #ADT-CustomADTLoadout

- type: chameleonOutfit
  id: ADTSeniorResearcherChameleonOutfit
  job: ADTSeniorResearcher
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    gloves: ClothingHandsGlovesLatex
