- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
# ADT-Tweak
  # requirements:
  #   - !type:DepartmentTimeRequirement
  #     department: Medical
  #     time: 36000 #10 hrs # Corvax-RoleTime
  #     inverted: true # stop playing intern if you're good at med!
# ADT-Tweak
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
#    belt: ClothingBeltMedicalFilled ADT tweak
    pocket2: BookMedicalReferenceBook
  #storage:
    #back:
    #- Stuff
