- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
  - !type:RoleTimeRequirement
    role: JobMedicalDoctor
    time: 14400 # 4 hrs Ganimed-RoleTime
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15 hrs Ganimed-RoleTime
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  canBeAntag: false # ADT tweak?
  access:
  - Medical
  - Maintenance
  - External # ADT tweak
  extendedAccess:
  - Chemistry

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
# ADT tweak Start
    ears: ADTClothingHeadsetParamedic
#    belt: ClothingBeltMedicalEMTFilled
# ADT tweak End
  storage:
    back:
    - EmergencyRollerBedSpawnFolded

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
