- type: job
  id: ADTMiner
  name: job-name-ADTMiner
  description: job-description-ADTminer
  playTimeTracker: JobADTMiner
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
  icon: "JobIconShaftMiner"
  startingGear: ADTMinerGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: ADTMinerGear
  equipment:
    pocket1: AppraisalTool
    eyes: ClothingEyesGlassesMeson
    pocket2: OreBag
  storage:
    back:
    - MineralScanner
    - FlashlightSeclite
    - MiningVoucher
    - MiningSuitVoucher
