- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleArmsDealer
  name: Arms Dealer Role
  components:
  - type: MindRole
    antagPrototype: ArmsDealer
    subtype: role-subtype-arms-dealer
  - type: ArmsDealerRole
