- type: job
  id: Magistrat
  name: job-name-magistrat
  description: job-description-magistrat
  playTimeTracker: JobMagistrat
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 108000 # 30 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 198000 # 55 hrs
    - !type:DepartmentTimeRequirement
      department: Juridical
      time: 108000 # 30 hrs
    - !type:AgeRequirement
      requiredAge: 30
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Vox
  startingGear: MagistratGear
  icon: "JobIconMagistrat"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Command
    - Brig
    - Maintenance
    - Service
    - Security
    - Magistrate
    - Lawyer
    - IAA
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MagistratGear
  equipment:
    eyes: ClothingEyesGlassesCommand
    id: MagistratPDA
    ears: ClothingHeadsetMagistrat
    belt: ClothingBeltStorageWaistbag
    pocket2: RubberStampMagisrat
  storage:
    back:
    - Flash
    - WeaponDisabler
    - Zipties
    - ADTtelescopicBaton
