- type: job
  id: ADTBattleShipCaptainKMT
  name: job-name-captain-kmt
  description: job-description-captain-kmt
  playTimeTracker: JobADTBattleShipCaptainKMT
  requirements:
    - !type:SexRequirement
      allowedSex:
      - Male
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Human
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000 #20 hrs 
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 #20 hrs 
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs 
    - !type:OverallPlaytimeRequirement
      time: 504000 #140 hrs 
  startingGear: ADTBattleShipCaptainKMTGear
  icon: "JobIconCaptainKMT"
  joinNotifyCrew: true
  supervisors: job-supervisors-kmt-highcommand
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - KMT
    - type: FriendlyFire
      enabled: true
    - type: FriendlyFireToggleable

- type: startingGear
  id: ADTBattleShipCaptainKMTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
