- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 14400 # 4 hours
  # ADT Restrict Start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
  # ADT RESTRICT End
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - ADTAccessCaptain #ADT-tweak - полный доступ ко всем станционным дверям, кроме ЦК и ОСЩ
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    # ears: ClothingHeadsetAltCommand # ADT tweak
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
    # - StationCharter
