- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ADTClothingEyesGlassesMed
        orGroup: BrigmedicGlasses # Ganimed-Tweak
      - id: ClothingEyesHudMedSec
        orGroup: BrigmedicGlasses # Ganimed-Tweak
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 4
      - id: ADTClothingModsuitBackBrigmedic
      - id: ClothingHandsGlovesNitrile
      - id: BrigmedicDuffelbagClothing
      - id: MedkitFilled
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.4
      - id: BoxSyringe
      - id: BoxPillCanister
      - id: BoxBodyBag
      - id: ChemistryBottleEpinephrine
        amount: 1
      - id: ADTHandheldCrewMonitorBrigmedic

- type: entity
  id: LockerBrigmedicFilled
  suffix: Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ADTClothingEyesGlassesMed
        orGroup: BrigmedicGlasses # Ganimed-Tweak
      - id: ClothingEyesHudMedSec
        orGroup: BrigmedicGlasses # Ganimed-Tweak
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 4
      - id: MedkitFilled
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.4
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.05
      - id: ClothingOuterVestSecurityMedic # Corvax-Resprite
        prob: 0.5
        orGroup: BrigmedicOuterClothing # Ganimed-Tweak
      - id: ClothingOuterCoatLabSecurityMedic # Corvax-Resprite
        prob: 0.5
        orGroup: BrigmedicOuterClothing # Ganimed-Tweak
      - id: BoxSyringe
      - id: BoxPillCanister
      - id: BoxBodyBag
      - id: ClothingHandsGlovesNitrile
      - id: ChemistryBottleEpinephrine
        amount: 1
      - id: BrigmedicDuffelbagClothing
      - id: ADTHandheldCrewMonitorBrigmedic
      - id: ADTBookSRPsec
      - id: ADTBookSRPmed
      - id: ADTBookPCDsec
