- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 90000 #25 hrs # ADT-RoleTime
  # ADT Restrict Start
  - !type:SpeciesRequirement
    inverted: true
    species:
    - Resomi
    - Vox
    - Shadekin
  # ADT RESTRICT End
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  # ADT-Tweak-Start: добавляем SecurityStaff для детектива
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff
  # ADT-Tweak-End

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    #id: DetectivePDA ADT: different PDAs in loadouts
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
