- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requireAdminNotify: true # Ganimed Rules Tweak
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 36000 #10 hrs Ganimed-RoleTime
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 3600 #1 hr, knowing how to use the tools is important
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 54000 #15 hrs Ganimed-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #30 hrs Ganimed-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 180000 #50 hrs Ganimed-RoleTime
    - !type:TraitsRequirement # Ganimed-MRP: HoS undergoes medical examination
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - ADTDeaf
      - Frail
    - !type:AgeRequirement # Ganimed-MRP
      requiredAge: 24
  # ADT Restrict Start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
      - Shadekin
  # ADT RESTRICT End
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom
      - type: AntagImmune # Ganimed-MRP: Loyalty implant
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom
      # ADT-Tweak-Start: метка персонала службы безопасности
      - type: SecurityStaff
      # ADT-Tweak-End

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA #Ganimed-Tweak
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
