- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10h # Corvax-RoleTime 1
    #- !type:RoleTimeRequirement
    #  role: JobDetective
    #  time: 1h # knowing how to use the tools is important
    #- !type:RoleTimeRequirement
    #  role: JobSecurityOfficer
    #  time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 50h # Corvax-RoleTime 10
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      species:
      - Resomi
      - Vox
      - Shadekin
  # ADT RESTRICT End
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom
      # ADT-Tweak-Start: метка персонала службы безопасности
      - type: SecurityStaff
      # ADT-Tweak-End

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    # id: HoSPDA ADT: different PDAs in loadouts
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
    - MagazinePistol

- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
