- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 54000 #15 hrs # ADT-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at security!
# ADT Restrict Start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
      - Shadekin
    # ADT RESTRICT End
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial # goobstation
    components:
      - type: SecurityStaff

- type: startingGear
  id: SecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: ADTBookSpaceLaw #ADT-WikiBooks
  storage:
    back:
    - Flash
    - MagazinePistol
