- type: startingGear
  id: ADTERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatERTLeaderBeret
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    neck: ClothingNeckMantleERTLeader
    outerClothing: ClothingOuterArmorBulletproof
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssault
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: PhoneInstrument
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - SpaceCash500
    - Truncheon
    - ClothingHeadHatERTLeaderBeret
    - DoorRemoteCommand
    - MedkitCombatFilled
    - HandHeldMassScanner
    - HandheldCrewMonitor
    - HandheldGPSBasic
    - ADTAdvancedHoloprojectorField
    belt:
    - WeaponDisabler
    - Handcuffs
    - Handcuffs
    - Whistle
    - ADTWeaponPistolDesertEagle
    - MagazineMagnum
    - FlashlightSeclite

- type: startingGear
  id: ADTERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ADTClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    neck: ClothingNeckMantleERTLeader
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssault
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - ADTertMechUplink
    - Truncheon
    - ClothingHeadHatERTLeaderBeret
    - DoorRemoteCommand
    - MedkitCombatFilled
    - HandHeldMassScanner
    - HandheldCrewMonitor
    - HandheldGPSBasic
    - ADTAdvancedHoloprojectorField
    belt:
    - WeaponDisabler
    - Handcuffs
    - Handcuffs
    - Whistle
    - ADTWeaponPistolDesertEagle
    - MagazineMagnum
    - FlashlightSeclite

- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ADTERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ADTERTLeaderGearEVARiot
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMag
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    mask: ClothingMaskGasERT
    outerClothing: ADTClothingOuterERTRiotHardsuit
    id: ERTLeaderPDA
    neck: ClothingNeckMantleERTLeader
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssault
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - SpaceCash500
    - ADTertRevolutionaryMechUplink
    - Truncheon
    - ClothingHeadHatERTLeaderBeret
    - DoorRemoteCommand
    - MedkitCombatFilled
    - HandHeldMassScanner
    - HandheldCrewMonitor
    - HandheldGPSBasic
    - ADTAdvancedHoloprojectorField
    belt:
    - WeaponDisabler
    - Handcuffs
    - Handcuffs
    - Whistle
    - ADTWeaponPistolDesertEagle
    - MagazineMagnum
    - FlashlightSeclite

#engie

- type: startingGear
  id: ADTERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsWork
    head: ClothingHeadHatBeretEngineering
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponPistolMk58
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - RCD
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - HandHeldMassScanner
    - MagazinePistol

- type: startingGear
  id: ADTERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - RCD
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - HandHeldMassScanner

- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ADTERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ADTERTEngineerGearEVARiot
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ADTClothingOuterERTRiotHardsuit
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - RCD
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass
    - PinpointerNuclear
    - SpaceCash500
    - HandHeldMassScanner

# Security

- type: startingGear
  id: ADTERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatBeretSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBulletproof
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssault
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTWeaponPistolDesertEagle
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - Truncheon
    - MagazineMagnum

- type: startingGear
  id: ADTERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssault
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - Truncheon

- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ADTERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ADTERTSecurityGearEVARiot
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ADTClothingOuterERTRiotHardsuit
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssault
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  inhand:
    - AirTankFilled
  storage:
    back:
    - BoxSurvivalEngineering
    - BoxZiptie
    - CrowbarRed
    - PinpointerNuclear
    - SpaceCash500
    - Truncheon

# Medical

- type: startingGear
  id: ADTERTMedicalGear
  equipment:
    jumpsuit: ADTClothingUniformJumpsuitCMOHike
    back: ClothingBackpackERTMedical
    shoes: ADTClothingShoesHighboots
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestArmorMedSec
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ADTClothingBeltMedicalSecurityERTFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponPistolMk58
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalMedical # Is this actually supposed to be Medical? All other ERT has Extended
    - ADTMedkitAdvancedERT
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - HandheldHealthAnalyzer
    - DefibrillatorCompact
    - MagazinePistol

- type: startingGear
  id: ADTERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ADTClothingBeltMedicalSecurityERTFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalMedical # Is this actually supposed to be Medical? All other ERT has Extended
    - ADTMedkitAdvancedERT
    - CrowbarRed
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - HandheldHealthAnalyzer
    - DefibrillatorCompact

- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ADTERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ADTERTMedicalGearEVARiot
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ADTClothingOuterERTRiotHardsuit
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ADTClothingBeltMedicalSecurityERTFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalMedical # Is this actually supposed to be Medical? All other ERT has Extended
    - ADTMedkitAdvancedERT
    - CrowbarRed
    - PinpointerNuclear
    - SpaceCash500
    - HandheldHealthAnalyzer
    - DefibrillatorCompact

#Janitor (ТЕПЕРЬ УЧЕНЫЙ)

- type: startingGear
  id: ADTERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHelmetERTJanitor
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterCoatLabOpened
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponLaserSvalinn
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponLaserSvalinn
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - AnomalyScanner
    - WeaponPistolCHIMP
    - NodeScanner
    - HandheldStationMap
    - CrowbarRed
    - Bible
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - BoxFolderClipboard
    - ClothingOuterStraightjacket
    - Bola
    - ADTMorphineBottle
    - ChemistryBottlePax
    - ChemistryBottlePax
    - ADTFormalinBottle
    - SyringeCryostasis
    - BoxBottle
    - BoxMouthSwab

- type: startingGear
  id: ADTERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponLaserSvalinn
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTBaseUplinkBOBERT
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - AnomalyScanner
    - WeaponPistolCHIMP
    - NodeScanner
    - HandheldStationMap
    - CrowbarRed
    - Bible
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - BoxFolderClipboard
    - ClothingOuterStraightjacket
    - Bola
    - ADTMorphineBottle
    - ChemistryBottlePax
    - ChemistryBottlePax
    - ADTFormalinBottle
    - SyringeCryostasis
    - BoxBottle
    - BoxMouthSwab

- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ADTERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ADTERTJanitorGearEVARiot
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    gloves: ClothingHandsGlovesCombat
    outerClothing: ADTClothingOuterERTRiotHardsuit
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponLaserSvalinn
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
    underwearb: ADTClothingUnderwearBottomBriefsWhite
    underweart: ADTClothingUnderwearTopTShirt
    socks: ADTClothingUnderwearSocksComfyGrey
  storage:
    back:
    - BoxSurvivalEngineering
    - AnomalyScanner
    - WeaponPistolCHIMP
    - NodeScanner
    - HandheldStationMap
    - CrowbarRed
    - Bible
    - PinpointerNuclear
    - FlashlightSeclite
    - SpaceCash500
    - BoxFolderClipboard
    - ClothingOuterStraightjacket
    - Bola
    - ADTMorphineBottle
    - ChemistryBottlePax
    - ChemistryBottlePax
    - ADTFormalinBottle
    - SyringeCryostasis
    - BoxBottle
    - BoxMouthSwab
