- type: job
  id: ADTBlueShieldOfficer
  name: job-name-ADTBlueShieldOfficer
  description: job-description-ADTBlueShieldOfficer
  playTimeTracker: JobADTBlueShieldOfficer
  requireAdminNotify: true # Ganimed Rules Tweak
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 #20 hrs Ganimed-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs Ganimed-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs Ganimed-RoleTime
    - !type:AgeRequirement
      requiredAge: 21
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
  # ADT RESTRICT End
    - !type:TraitsRequirement # Ganimed-MRP: BSO undergoes medical examination
      inverted: true
      traits:
      - Pacifist
      - Blindness
      - Frail
  weight: 15
  startingGear: ADTBlueShieldOfficerGear
  icon: "JobIconADTBlueShieldOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Captain
    - Command
    - Brig
    - Security
    - Armory
    - Maintenance
    - Service
    - External
    - Research
    - Medical
    - Engineering
    - Cargo
    - BlueShield
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
      components:
        - type: BlueShield
        - type: CantShoot
          popup: combo-cantshoot
          whitelist:
            tags:
            - ADTBsoWeapon
        - type: Necksnap
        - type: Combo
          availableMoves:
            - actionsNeeds:
                - Grab
                - Hit
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-slam-end
                - !type:ComboDamageEffect
                  damage:
                    types:
                      Blunt: 10
                - !type:ComboFallEffect
                - !type:ComboStopGrabEffect
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
            - actionsNeeds:
                - Hit
                - Hit
              comboEvent:
                - !type:ComboEffectToStuned
                  comboEvents:
                  - !type:ComboEffectSleep
                    time: 5
                - !type:ComboMoreDamageToDownedEffect
                  damage:
                    types:
                      Blunt: 15
                - !type:ComboPopupEffect
                  localeText: combo-cqc-kick-end
                - !type:ComboDamageEffect
                  damage:
                    types:
                      Blunt: 10
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
                - !type:ComboTrowTargetEffect
                - !type:ComboStaminaDamageEffect
                  staminaDamage: 25
            - actionsNeeds:
                - Disarm
                - Grab
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-cqc-pressure-end
                - !type:ComboStaminaDamageEffect
                  staminaDamage: 35
                - !type:ComboHandsRetakeEffect
            - actionsNeeds:
                - Grab
                - Grab
              stopGrab: false
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-cqc-restain-end
                - !type:ComboFallEffect
                  dropItems: true
                - !type:ComboStaminaDamageEffect
                  staminaDamage: 55
            - actionsNeeds:
                - Disarm
                - Disarm
                - Hit
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-cqc-consecutive-end
                - !type:ComboMoreDamageToDownedEffect
                  damage:
                    types:
                      Blunt: 25
                - !type:ComboFallEffect
                - !type:ComboStaminaDamageEffect
                  staminaDamage: 60
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
            - actionsNeeds:
                - Grab
                - Disarm
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-leg-sweep-end
                - !type:ComboFallEffect
                - !type:ComboStopGrabEffect
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
            - actionsNeeds:
                - Crawl
                - Crawl
              comboEvent:
                - !type:ComboEffectToUserPuller
                  comboEvents:
                  - !type:ComboDamageEffect
                    damage:
                      types:
                        Blunt: 10
                  - !type:ComboTrowOnUserEffect
                  - !type:ComboStopTargetGrabEffect
                  - !type:ComboStunEffect
                    stunTime: 1
                    dropItems: false
                  - !type:ComboPopupEffect
                    localeText: combo-leg-sweep-end
        - type: AntagImmune # Ganimed-MRP: Loyalty implant

- type: startingGear
  id: ADTBlueShieldOfficerGear
  equipment:
    eyes: ADTClothingEyesGlassesBlueshield
    shoes: ClothingShoesBootsCombatFilled
    belt: ADTClothingBeltMedicalSecurityFilled
    gloves: ClothingHandsGlovesCombat
    id: ADTBlueshieldOfficerPDA
    pocket1: ADTBlueshieldVoucher
    pocket2: ADTHandheldCrewMonitorBlueshield

- type: chameleonOutfit
  id: ADTBlueShieldChameleonOutfit
  job: ADTBlueShieldOfficer
  hasMindShield: true
  equipment:
    eyes: ADTClothingEyesGlassesBlueshield
    shoes: ClothingShoesBootsCombatFilled
    belt: ADTClothingBeltMedicalSecurityFilled
    gloves: ClothingHandsGlovesCombat
    id: ADTBlueshieldOfficerPDA
