- type: job
  id: ADTBlueShieldOfficer
  name: job-name-ADTBlueShieldOfficer
  description: job-description-ADTBlueShieldOfficer
  playTimeTracker: JobADTBlueShieldOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobCaptain
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 18000 #5 hrs
    - !type:AgeRequirement
      requiredAge: 21
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
  weight: 15
  startingGear: ADTBlueShieldOfficerGear
  icon: "JobIconADTBlueShieldOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Captain
    - Command
    - Brig
    - Security
    - Armory
    - Maintenance
    - Service
    - External
    - Research
    - Medical
    - Engineering
    - Cargo
    - BlueShield
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
      components:
        - type: CantShoot
          popup: combo-cantshoot
          whitelist:
            tags:
            - ADTBsoWeapon
        - type: Puller
          grabStats:
            None:
              requiredHands: 1
              doaftersToEscape: 0
              movementSpeedModifier: 0.9
              escapeAttemptTime: 0
              setStageTime: 0
            Soft:
              requiredHands: 1
              doaftersToEscape: 3
              movementSpeedModifier: 0.8
              escapeAttemptTime: 1.2
              setStageTime: 0
            Hard:
              requiredHands: 1
              doaftersToEscape: 4
              movementSpeedModifier: 0.75
              escapeAttemptTime: 1.2
              setStageTime: 0.75
            Choke:
              requiredHands: 2
              doaftersToEscape: 5
              movementSpeedModifier: 0.7
              escapeAttemptTime: 1.25
              setStageTime: 1.25
        - type: MeleeWeapon
          attackRate: 2
          animation: WeaponArcFist
          damage:
            types:
              Blunt: 6
        - type: Combo
          availableMoves:
            - actionsNeeds:
                - Grab
                - Hit
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-slam-end
                - !type:ComboDamageEffect
                  damage:
                    types:
                      Blunt: 10
                - !type:ComboFallEffect
                - !type:ComboStopGrabEffect
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
            - actionsNeeds:
                - Hit
                - Disarm
                - Hit
              comboEvent:
                - !type:ComboMoreDamageToDownedEffect
                  damage:
                    types:
                      Blunt: 20
                - !type:ComboPopupEffect
                  localeText: combo-cqc-kick-end
                - !type:ComboDamageEffect
                  damage:
                    types:
                      Blunt: 15
                - !type:ComboStunEffect
                  stunTime: 2
                  dropItems: false
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
                - !type:ComboTrowTargetEffect
            - actionsNeeds:
                - Disarm
                - Grab
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-cqc-pressure-end
                - !type:ComboStaminaDamageEffect
                  staminaDamage: 65
            - actionsNeeds:
                - Grab
                - Grab
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-cqc-restain-end
                - !type:ComboStunEffect
                  stunTime: 4
            - actionsNeeds:
                - Disarm
                - Disarm
                - Hit
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-cqc-consecutive-end
                - !type:ComboMoreDamageToDownedEffect
                  damage:
                    types:
                      Blunt: 25
                - !type:ComboFallEffect
                - !type:ComboStaminaDamageEffect
                  staminaDamage: 60
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
            - actionsNeeds:
                - Grab
                - Disarm
              comboEvent:
                - !type:ComboPopupEffect
                  localeText: combo-leg-sweep-end
                - !type:ComboFallEffect
                - !type:ComboStopGrabEffect
                - !type:ComboAudioEffect
                  sound:
                    collection: GenericHit
            - actionsNeeds:
                - Crawl
                - Crawl
              comboEvent:
                - !type:ComboEffectToUserPuller
                  comboEvents:
                  - !type:ComboDamageEffect
                    damage:
                      types:
                        Blunt: 10
                  - !type:ComboTrowOnUserEffect
                  - !type:ComboStopTargetGrabEffect
                  - !type:ComboStunEffect
                    stunTime: 1
                    dropItems: false
                  - !type:ComboPopupEffect
                    localeText: combo-leg-sweep-end

- type: startingGear
  id: ADTBlueShieldOfficerGear
  equipment:
    eyes: ADTClothingEyesGlassesBlueshield
    shoes: ClothingShoesBootsCombatFilled
    belt: ADTClothingBeltMedicalSecurityFilled
    gloves: ClothingHandsGlovesCombat
    id: ADTBlueshieldOfficerPDA
    pocket1: ADTBlueshieldVoucher
    pocket2: ADTHandheldCrewMonitorBlueshield
