- type: latheRecipePack
  id: ADTMagazineStaticPack
  recipes:
  - ADTMagazineMagnum
  - ADTMagazineMagnumEmpty

- type: latheRecipePack
  id: ADTMagazineUraniumPack
  recipes:
  - ADTMagazineMagnumIncendiary
  - ADTMagazineMagnumUranium

- type: latheRecipePack
  id: ADTAttachmentPack
  recipes:
  - ADTAttachmentVerticalGripRecipe
  - ADTAttachmentLaserSightRecipe
  - ADTAttachmentReflexSightRecipe
  - ADTAttachmentT2MiniscopeRecipe
  - ADTAttachmentM90UnderbarrelShotgunRecipe
  - ADTAttachmentM90GrenadeLauncherRecipe

- type: latheRecipePack
  id: ADT40mmGrenadePack
  recipes:
  - ADT40mmGrenadeBatonRecipe
  - ADT40mmGrenadeEMPRecipe
  - ADT40mmGrenadeFlashRecipe
  - ADT40mmGrenadeSmokeRecipe

- type: latheRecipePack
  id: ADTMechEquipmentSecTechfabPack
  recipes:
  # - MechEquipmentArmorMelee Вырезано из-за неработоспособности
  # - MechEquipmentArmorRange Вырезано из-за неработоспособности
  - ADTMechGunImmolatorLaser
  - ADTMechGunPeacemakerDisabler
  - ADTMechGunSolarisLaserCannon
  - ADTMechGunTeslaCannon
  - ADTMechGunScattershot
  - ADTMechGunUltraAC2
  - ADTMechGunFNX99Hades    
  # - ADTMechGunMHAR21       Вырезано ради баланса
  - ADTMechGunSGL6          
  - ADTMechGunBRM6          
  # - ADTMechGunSRM8         Вырезано ради баланса   
  - ADTBoxAmmoAC2Ultra
  - ADTBoxAmmoScattershot
  - ADTBoxAmmoHades         
  # - ADTBoxAmmoSniper       Вырезано ради баланса
  - ADTBoxAmmoGranade 
