- type: latheRecipePack
  id: ADTPrinterStaticPack
  recipes:
  - PrintedDocumentReportStationRecipe
  - PrintedDocumentReportOnEliminationOfViolationsRecipe
  - PrintedDocumentReporDepartmentRecipe
  - PrintedDocumentReportEmployeePerformanceRecipe
  - PrintedDocumentReportOnTheChaptersMeetingRecipe
  - PrintedDocumentInternalAffairsAgentsReportRecipe
  - PrintedDocumentConditionReportRecipe
  - PrintedDocumentReportStudyObjectRecipe
  - PrintedDocumentExperimentReportRecipe
  - PrintedDocumentDisposalReportRecipe
  - PrintedDocumentApplicationAppointmentInterimRecipe
  - PrintedDocumentApplicationEmploymentRecipe
  - PrintedDocumentLetterResignationRecipe
  - PrintedDocumentApplicationAccessRecipe
  - PrintedDocumentApplicationEquipmentRecipe
  - PrintedDocumentAppealRecipe
  - PrintedDocumentEvacuationShuttleRequestRecipe
  - PrintedDocumentShuttleRegistrationRequestRecipe
  - PrintedDocumentRequestCallMembersCentralCommitteeDSORecipe
  - PrintedDocumentRequestRequestToEstablishThreatLevelRecipe
  - PrintedDocumentRequestChangeSalaryRecipe
  - PrintedDocumentRequestForNonlistedEmploymentRecipe
  - PrintedDocumentRequestForPromotionRecipe
  - PrintedDocumentRequestDocumentsRecipe
  - PrintedDocumentRequestEuthanasiaRecipe
  - PrintedDocumentRequestConstructionWorkRecipe
  - PrintedDocumentRequestModernizationRecipe
  - PrintedDocumentComplaintViolationLaborRulesRecipe
  - PrintedDocumentComplaintOffenseRecipe
  - PrintedDocumentPermissionEquipmentRecipe
  - PrintedDocumentPermissionToTravelInCaseOfThreatRecipe
  - PrintedDocumentSearchPermissionRecipe
  - PrintedDocumentPermissionToCarryWeaponsRecipe
  - PrintedDocumentPrescriptionDrugAuthorizationRecipe
  - PrintedDocumentPermissionDisposeBodyRecipe
  - PrintedDocumentConstructionPermitRecipe
  - PrintedDocumentPermissionToExtendMarriageRecipe
  - PrintedDocumentOrderDismissalRecipe
  - PrintedDocumentOrderDeprivationAccessRecipe
  - PrintedDocumentOrderEncouragementRecipe
  - PrintedDocumentOrderParolePrisonerRecipe
  - PrintedDocumentOrderRecognizingSentienceCreatureRecipe
  - PrintedDocumentOrderMedicalInterventionRecipe
  - PrintedDocumentProductManufacturingOrderRecipe
  - PrintedDocumentOrderPurchaseResourcesEquipmentRecipe
  - PrintedDocumentOrderingSpecialEquipmentRecipe
  - PrintedDocumentOrderPurchaseWeaponsRecipe
  - PrintedDocumentCertificateRecipe
  - PrintedDocumentCertificateAdvancedTrainingRecipe
  - PrintedDocumentCertificateOffenseRecipe
  - PrintedDocumentDeathCertificateRecipe
  - PrintedDocumentMarriageCertificateRecipe
  - PrintedDocumentDivorceCertificateRecipe
  - PrintedDocumentClosingIndictmentRecipe
  - PrintedDocumentSentenceRecipe
  - PrintedDocumentJudgmentRecipe
  - PrintedDocumentStatementHealtheRecipe
  - PrintedDocumentDecisionToStartTrialRecipe

- type: latheRecipePack
  id: ADTPrinterEmagPack
  recipes:
  - PrintedDocumentErrorLoadingFormHeaderRecipe
  - PrintedDocumentNoticeOfLiquidationRecipe
  - PrintedDocumentBusinessDealRecipe
  - PrintedDocumentNoteBeginningMilitaryActionsRecipe
  - PrintedDocumentReportAccomplishmentGoalsRecipe

- type: latheRecipePack
  id: ADTRecorderStaticPack
  recipes:
  - CassetteTape
  - TapeRecorder

- type: latheRecipePack
  id: ADTServiceStaticPack
  recipes:
  - DrinkFlaskBar
  - DrinkVacuumFlask
  - DrinkIceBucket
  - DrinkShaker
  - DrinkJigger
  - Spoon
  - Fork
  - BarSpoon
  - Urn
  - BoxFolderRed
  - BoxFolderBlue
  - BoxFolderYellow
  - BoxFolderWhite
  - BoxFolderGrey
  - BoxFolderBlack
  - BoxFolderGreen

- type: latheRecipePack
  id: ADTServiceHydroponics
  recipes:
  - ADTAdvancedPlantAnalyzer

- type: latheRecipePack
  id: ADTWeaponLauncherHydraPack
  recipes:
  - ADTWeaponLauncherHydra
  - GrenadeCleanade

- type: latheRecipePack
  id: ADTArcade
  recipes:
  - ADTBlockGameArcadeComputerCircuitboard
  - ADTSpaceVillainArcadeComputerCircuitboard
  - ADTMinesweeperCircuitboard
