- type: playTimeTracker
  id: JobMagistrat

- type: playTimeTracker
  id: JobADTPathologist

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobADTBlueShieldOfficer

- type: playTimeTracker
  id: JobADTSeniorPhysician

- type: playTimeTracker
  id: JobADTSeniorResearcher

- type: playTimeTracker
  id: JobADTSeniorEngineer

- type: playTimeTracker
  id: JobADTSeniorOfficer

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobTimePatrol

- type: playTimeTracker
  id: JobADTGuardOfficer

- type: playTimeTracker
  id: JobADTUSSPArmyOfficer

- type: playTimeTracker
  id: JobADTUSSPArmyPrivate

- type: playTimeTracker
  id: JobADTBarber

- type: playTimeTracker
  id: JobADTMiner
