- type: playTimeTracker
  id: JobMagistrat

- type: playTimeTracker
  id: JobADTPathologist

- type: playTimeTracker
  id: JobRoboticist

- type: playTimeTracker
  id: JobADTBlueShieldOfficer

- type: playTimeTracker
  id: JobADTSeniorPhysician

- type: playTimeTracker
  id: JobBrigmedic

