- type: job
  id: ADTBattleShipGunnerKMT
  name: job-name-gunner-kmt
  description: job-description-gunner-kmt
  playTimeTracker: JobADTBattleShipGunnerKMT
  requirements:
    - !type:SexRequirement
      allowedSex:
      - Male
    - !type:SpeciesRequirement
      inverted: false
      species:
      - Human
  startingGear: ADTBattleShipGunnerKMTGear
  icon: "JobIconGunnerKMT"
  supervisors: job-supervisors-kmt-gunner
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - KMT
    - type: FriendlyFire
      enabled: true
    - type: FriendlyFireToggleable

- type: startingGear
  id: ADTBattleShipGunnerKMTGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ADTClothingModsuitBackSyndicate #ADT tweak
    # mask: ClothingMaskGasSyndicate ADT tweak
    # eyes: ClothingEyesHudSyndicate ADT tweak
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    # outerClothing: ClothingOuterHardsuitSyndie ADT tweak
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltAssault #ADT nukebuff
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter
