- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - ADTMiner # ADT tweak
  - SalvageSpecialist

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - ADTBarber # ADT-Tweak

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  # - ERTChaplain # adt tweak, надо сначала добавить эту роль
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  # ADT-Tweak
  - ADTBlueShieldOfficer
  - Magistrat
  # ADT-Tweak
  - IAA # Corvax-IAA
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  # - CentralCommandOfficial втф ADT
  # - CBURN
  # - ERTLeader
  # - ERTChaplain
  # - ERTJanitor
  # - ERTMedical
  # - ERTSecurity
  # - ERTEngineer
  # - DeathSquad
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  - ADTSeniorEngineer # ADT-Tweak

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  # ADT-Tweak
  - ADTPathologist
  - ADTSeniorPhysician
  # ADT-Tweak

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  # - Pilot # Corvax-Pilot
  - Detective
  - Warden
  # ADT-Tweak
  - Brigmedic
  - ADTSeniorOfficer
  - ADTGuardOfficer
  # ADT-Tweak

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant
  # ADT-Tweak
  - ADTRoboticist
  - ADTSeniorResearcher
  # ADT-Tweak

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  # - Pilot # Corvax-Pilot
  - ADTBarber # ADT-Tweak
  primary: false
