- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  # ADT-Tweak-start
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
  # ADT-tweak-end
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
#    - BoxSurvivalMedical
    - RubberStampPsychologist # Corvax-MRP
