- type: job
  id: ADTSeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobADTSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 216000 # 60 hrs
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    eyes: ADTClothingEyesGlassesMedChem
  storage:
    back:
    - ADTHumanCubeWrapped #ADT-CustomADTLoadout

- type: chameleonOutfit
  id: ADTSeniorPhysicianChameleonOutfit
  job: ADTSeniorPhysician
  hasMindShield: true
  equipment:
    ears: ClothingHeadsetMedical
    eyes: ADTClothingEyesGlassesMedChem