- type: job
  id: ADTSeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobADTSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 6h
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 60h
  weight: 9
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    eyes: ADTClothingEyesGlassesMedChem
  storage:
    back:
    - ADTHumanCubeWrapped #ADT-CustomADTLoadout

- type: chameleonOutfit
  id: ADTSeniorPhysicianChameleonOutfit
  job: ADTSeniorPhysician
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabSeniorPhysician
    gloves: ClothingHandsGlovesLatex
