- type: job
  id: ADTSeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobADTSeniorOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 28800 #8 hrs #ADT-RoleTime
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 14400 #4 hrs #ADT-RoleTime
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 28800 #8 hrs #ADT-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 234000 # 65 hrs #ADT-RoleTime
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponRevolverDeckard
    pocket2: SpeedLoaderMagnum
