- type: job
  id: ADTSeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobADTSeniorOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 28800 #8 hrs
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 14400 #4 hrs
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 28800 #8 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 234000 # 65 hrs
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
      - Vox
#      - Shadekin
  # ADT RESTRICT End
    - !type:AgeRequirement # Ganimed-MRP
      requiredAge: 21
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  extendedAccess: # Ganimed-Tweak
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponRevolverDeckard
    pocket2: SpeedLoaderMagnum

- type: chameleonOutfit
  id: ADTSeniorOfficerChameleonOutfit
  job: ADTSeniorOfficer
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity