- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs
#    - !type:OverallPlaytimeRequirement
#      time: 36000 #10 hrs
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: SalvagePDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool #ADT start
    pocket2: OreBag
  storage:
    back:
    - MineralScanner
    - FlashlightSeclite
    - MiningVoucher
    - MiningSuitVoucher
    # ADT end
