- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs
#    - !type:OverallPlaytimeRequirement
#      time: 36000 #10 hrs
# ADT Restrict Start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Resomi
  # ADT RESTRICT End
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
#    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist #ADT tweak
    #id: SalvagePDA # ADT: different PDAs in loadouts
    # ears: ClothingHeadsetCargo # ADT tweak
    pocket1: AppraisalTool #ADT start
    eyes: ClothingEyesGlassesMeson
    pocket2: OreBag
  storage:
    back:
    - MineralScanner
    - FlashlightSeclite
    - MiningVoucher
    - MiningSuitVoucher
    # ADT end
