- type: department
  id: Juridical
  name: department-Juridical
  description: department-Juridical-description
  color: "#777777"
  roles:
  - Magistrat
  - IAA
  - Lawyer

- type: department
  id: CentcomSpecialists 
  name: department-CentcomSpecialists
  description: department-CentcomSpecialists-description
  color: "#2681a5"
  roles:
  - ADTCentcomConsultant
  - ADTBlueShieldOfficer
