[game]
hostname = "[RU][MRP] üöÄ Enterprise ‚Äî –ù–æ–≤–æ–µ –ø—É—Ç–µ—à–µ—Å—Ç–≤–∏–µ"
desc = "Enterprise ‚Äî –ª–∞–º–ø–æ–≤—ã–π, –æ—Ä–∏–µ–Ω—Ç–∏—Ä–æ–≤–∞–Ω–Ω—ã–π –Ω–∞ —Å–æ–æ–±—â–µ—Å—Ç–≤–æ —Å–µ—Ä–≤–µ—Ä, —Å –ø—Ä–∏—è—Ç–Ω–æ–π –∏–≥—Ä–æ–≤–æ–π –∞—Ç–º–æ—Å—Ñ–µ—Ä–æ–π, —É–Ω–∏–∫–∞–ª—å–Ω—ã–º–∏ —Ñ–∏—à–∫–∞–º–∏, –Ω–∞—Å—ã—â–µ–Ω–Ω—ã–º–∏ —Ä–∞—É–Ω–¥–∞–º–∏ –∏ –ø–æ–≤—ã—à–µ–Ω–Ω—ã–º —É—Ä–æ–≤–Ω–µ–º –†–ü. \n–û—Ç–∑—ã–≤—á–∏–≤–∞—è –∞–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏—è, –¥—Ä—É–∂–µ–ª—é–±–Ω–∞—è –∫ –Ω–æ–≤–∏—á–∫–∞–º, –º–æ–∂–µ—Ç –ø–æ–º–æ—á—å –≤–∞–º –Ω–∞ –ª—é–±–æ–º —ç—Ç–∞–ø–µ –∏–≥—Ä—ã! \n–ß—Ç–æ –≤—ã –º–æ–∂–µ—Ç–µ –ø–æ–ª—É—á–∏—Ç—å, –∏–≥—Ä–∞—è —É –Ω–∞—Å?\n ‚ï≠ üî• Chaotic-Medium ‚Äî –±–∞–ª–∞–Ω—Å –º–µ–∂–¥—É —Ö–∞–æ—Ç–∏—á–Ω—ã–º–∏ –∏ —Å–ø–æ–∫–æ–π–Ω—ã–º–∏ —Ä–∞—É–Ω–¥–∞–º–∏;\n ‚îÉ üî© –ú–µ—Ö–∏ –∏ –ª–∞–≤–∞–ª–µ–Ω–¥;\n ‚îÉ üî™ –ü—Ä–æ—Ä–∞–±–æ—Ç–∞–Ω–Ω—ã–π –ª–æ—Ä, –Ω–∞ –æ—Å–Ω–æ–≤–µ –∫–æ—Ç–æ—Ä–æ–≥–æ –ø—Ä–æ–≤–æ–¥—è—Ç—Å—è –∏–≤–µ–Ω—Ç—ã;\n ‚îÉ üë• –û—Å–æ–±–µ–Ω–Ω—ã–µ –∏–≥—Ä–æ–≤—ã–µ —Ä–æ–ª–∏ —Å —à–∏—Ä–æ–∫–æ–π –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å—é –ø–µ—Ä—Å–æ–Ω–∞–ª–∏–∑–∞—Ü–∏–∏;\n ‚îÉ ‚ú® –ú–Ω–æ–∂–µ—Å—Ç–≤–æ –∏–≥—Ä–∞–±–µ–ª—å–Ω—ã—Ö —Ä–∞—Å –∏ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö –∞–Ω—Ç–∞–≥–æ–Ω–∏—Å—Ç–æ–≤.\n ‚ï∞ üîò –≠—Ç–æ –∏ –º–Ω–æ–≥–æ–µ –¥—Ä—É–≥–æ–µ –Ω–∞ Enterprise!"
maxplayers = 60
soft_max_players = 50
map_rotation = true
fallbackpreset = "extended"
lobbyenabled = true
role_timers = true
contraband_examine = false
lobbyduration = 300

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 256

[shuttle]
auto_call_time = 180
emergency_early_launch_allowed = true

[infolinks]
discord = "https://discord.gg/5JdpCD9rqM"
github = "https://github.com/CrimeMoot/Ganimed14/"
wiki = "https://station-enterprise.space"
patreon = "https://boosty.to/enterprisess14"
appeal = "https://discord.gg/5JdpCD9rqM"
bug_report = "https://github.com/CrimeMoot/Ganimed14/issues/new/choose"
website = "https://station-enterprise.space"

[server]
lobby_name = "Ô∏èEnterprise ‚Äî –ù–æ–≤–æ–µ –ø—É—Ç–µ—à–µ—Å—Ç–≤–∏–µ!"
rules_file = "GanimedRuleset"

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
preset_enabled = false
restart_enabled = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 10
min_overall_minutes = 0
deny_vpn = false
enable_without_admins = true
disable_with_admins = true

[atmos]
space_wind = true

[ic]
flavor_text = true

[discord]
ahelp_webhook = "*"
ahelp_avatar = "*"
round_update_webhook = "*"
round_end_role = "*"
ban_webhook = "*"

[rules]
time = 60

[admin]
admins_count_in_playercount = true
admins_count_for_max_players = true
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 1440

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e"
server_url = "*"
hub_urls = "https://hub.spacestation14.com/"

[sponsor]
api_url = "http://80.87.197.41:8081/api"