- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  requirements: # Ganimed-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5 hrs
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 18000 # 5 hrs
  startingGear: ADTCBURNGear # ADT tweak
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CBURNGear
  abstract: true  # ADT tweak Используйте ADTCBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: MagazineShotgun # ADT tweak
    pocket2: WeaponLaserGun
    belt: ADTClothingBeltBandolierFilledIncendiary # ADT tweak
  storage:
    back:
    - BoxSurvivalEngineering #ADT-tweak
#    - WeaponShotgunDoubleBarreled #ADT-tweak
#    - BoxShotgunIncendiary #ADT-tweak
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol
    # ADT Tweak (Add) start
    - WeaponShotgunEnforcer
    - Chainsaw
    - MedkitCombatFilled
    - MagazineShotgunIncendiary
    - SpaceCash500
    # ADT Tweak (Add) end

- type: chameleonOutfit
  id: CBURNChameleonOutfit
  job: CBURN
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetCBURN
    neck: ClothingNeckScarfStripedBrown
