- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: MagazineShotgun # ADT tweak
    pocket2: WeaponLaserGun
    belt: ADTClothingBeltBandolierFilledIncendiary # ADT tweak
  storage:
    back:
    - BoxSurvivalEngineering #ADT-tweak
#    - WeaponShotgunDoubleBarreled #ADT-tweak
#    - BoxShotgunIncendiary #ADT-tweak
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol
    # ADT Tweak (Add) start
    - WeaponShotgunEnforcer
    - Chainsaw
    - MedkitCombatFilled
    - MagazineShotgunIncendiary
    - SpaceCash500
    # ADT Tweak (Add) end
