- type: job
  id: DeathSquad
  name: job-name-deathsquad
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, RadioImplantCentcomm, FreedomImplant, DeathAcidifierImplant ]

- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingDeathSquadronBackpack
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesGlassesThermal
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ADTClothingShoesBootsMagERT #ADT tweak
    id: DeathsquadPDA
    pocket1: EnergySwordDouble
    pocket2: DoubleEmergencyOxygenTankFilled
    belt: ClothingBeltAssault
  storage:
    back:
    - ADTWeaponRifleTAR60SF
    - ADTMagazineRifleAR12
    - ADTMagazineRifleAR12
    - ADTMagazineRifleAR12
    - ADTMagazineRifleAR12
    - MagazineBoxRifleBig
    - WeaponRevolverMatebaAP
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - ToolDebug # spanish army knife
    - WelderExperimental
    - C4
    - C4
    - JawsOfLife
    - BoxMRE
    - ADTAttachmentVerticalGrip
    - ADTAttachmentAntiLyingWarrior
    - ADTAttachmentMagneticHarness
    - DefibrillatorCompact
    - PowerCellHyper
    - HandheldCrewMonitor
    - PinpointerNuclear
    - HandheldGPSBasic
    - HandHeldMassScanner
    - ADTCqcManual
    belt:
    - ADTCombatHypospray
    - WeaponTaser
    - ADTCrisisAutoInjector
    - Handcuffs
    - Handcuffs
    - ChemistryBottleOmnizine
    - ChemistryBottleOmnizine
    - ChemistryBottleEphedrine
    - ChemistryBottleEphedrine
  inhand:
  - WeaponPulseRifle

