- type: latheRecipe
  id: ADTMagazineMagnumEmpty
  result: MagazineMagnumEmpty
  completetime: 5
  materials:
    Lead : 25

- type: latheRecipe
  id: ADTMagazineMagnum
  result: MagazineMagnum
  completetime: 5
  materials:
    Lead : 170

- type: latheRecipe
  id: ADTMagazineMagnumIncendiary
  result: ADTMagazineMagnumIncendiary
  completetime: 5
  materials:
    Lead : 25
    Plastic: 145

- type: latheRecipe
  id: ADTMagazineMagnumUranium
  result: MagazineMagnumUranium
  completetime: 5
  materials:
    Lead : 25
    Plastic: 145
    Uranium: 125

- type: latheRecipe
  id: ADTMagazineShotgunUranium
  result: MagazineShotgunUranium
  completetime: 5
  materials:
    Steel: 50
    Plastic: 190
    Lead: 100
    Uranium: 130

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: ADTWeaponIonRifle
  result: ADTWeaponIonRifle
  materials:
    Steel: 2000
    Glass: 600
    Plastic: 600
    Gold: 200

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: ADTWeaponIonCarbine
  result: ADTWeaponIonCarbine
  materials:
    Steel: 1500
    Glass: 400
    Plastic: 400
    Gold: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesser
  result: ADTMagazineBoxMagnumLesser
  materials:
    Lead : 240

#Silver for HW
- type: latheRecipe
  id: ADTMagazineBoxMagnumSilver
  result: ADTMagazineBoxMagnumSilver
  completetime: 5
  materials:
    Lead : 145
    Silver: 145
    Plastic: 240

- type: latheRecipe
  id: ADTCartridgeMagnumsilver
  result: ADTCartridgeMagnumsilver
  completetime: 5
  materials:
    Lead : 10
    Silver: 20
# Silver for HW end

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesserIncendiary
  result: ADTMagazineBoxMagnumLesserIncendiary
  materials:
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesserPractice
  result: ADTMagazineBoxMagnumLesserPractice
  materials:
    Lead : 60

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesserUranium
  result: ADTMagazineBoxMagnumLesserUranium
  materials:
    Plastic: 240
    Uranium: 180

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserEmpty
  result: ADTSpeedLoaderMagnumLesserEmpty
  materials:
    Lead : 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesser
  result: ADTSpeedLoaderMagnumLesser
  materials:
    Lead : 180

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserPractice
  result: ADTSpeedLoaderMagnumLesserPractice
  materials:
    Lead : 85

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserUranium
  result: ADTSpeedLoaderMagnumLesserUranium
  materials:
    Lead : 50
    Plastic: 145
    Uranium: 105

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserIncendiary
  result: ADTSpeedLoaderMagnumLesserIncendiary
  materials:
    Lead : 50
    Plastic: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTWeaponTonfa
  result: ADTWeaponTonfa
  materials:
    Wood: 1500
    Steel: 500

- type: latheRecipe
  id: ADTGrenadeStinger
  result: GrenadeStinger
  completetime: 4
  materials:
    Lead : 800
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTHardsuitRaider
  result: ADTHardsuitRaider
  materials:
    Steel: 6000
    Glass: 3000
    Plasteel: 3000
    Copper: 800
