- type: latheRecipe
  id: ADTMagazineMagnumEmpty
  result: MagazineMagnumEmpty
  completetime: 5
  materials:
    Steel: 25

- type: latheRecipe
  id: ADTMagazineMagnum
  result: MagazineMagnum
  completetime: 5
  materials:
    Steel: 170

- type: latheRecipe
  id: ADTMagazineMagnumIncendiary
  result: ADTMagazineMagnumIncendiary
  completetime: 5
  materials:
    Steel: 25
    Plastic: 145

- type: latheRecipe
  id: ADTMagazineMagnumUranium
  result: MagazineMagnumUranium
  completetime: 5
  materials:
    Steel: 25
    Plastic: 145
    Uranium: 125

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: ADTWeaponIonRifle
  result: ADTWeaponIonRifle
  materials:
    Steel: 2000
    Glass: 600
    Plastic: 600
    Gold: 200

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: ADTWeaponIonCarbine
  result: ADTWeaponIonCarbine
  materials:
    Steel: 1500
    Glass: 400
    Plastic: 400
    Gold: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesser
  result: ADTMagazineBoxMagnumLesser
  materials:
    Steel: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesserIncendiary
  result: ADTMagazineBoxMagnumLesserIncendiary
  materials:
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesserPractice
  result: ADTMagazineBoxMagnumLesserPractice
  materials:
    Steel: 60

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTMagazineBoxMagnumLesserUranium
  result: ADTMagazineBoxMagnumLesserUranium
  materials:
    Plastic: 240
    Uranium: 180

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserEmpty
  result: ADTSpeedLoaderMagnumLesserEmpty
  materials:
    Steel: 50

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesser
  result: ADTSpeedLoaderMagnumLesser
  materials:
    Steel: 180

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserPractice
  result: ADTSpeedLoaderMagnumLesserPractice
  materials:
    Steel: 85

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserUranium
  result: ADTSpeedLoaderMagnumLesserUranium
  materials:
    Steel: 50
    Plastic: 145
    Uranium: 105

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTSpeedLoaderMagnumLesserIncendiary
  result: ADTSpeedLoaderMagnumLesserIncendiary
  materials:
    Steel: 50
    Plastic: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTWeaponTonfa
  result: ADTWeaponTonfa
  materials:
    Wood: 1500
    Steel: 500

- type: latheRecipe
  id: ADTGrenadeStinger
  result: GrenadeStinger
  completetime: 4
  materials:
    Steel: 800
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: ADTHardsuitRaider
  result: ADTHardsuitRaider
  materials:
    Steel: 6000
    Glass: 3000
    Plasteel: 3000
