# Base Prototypes
- type: latheRecipe
  abstract: true
  id: BaseDrinkShaker
  completetime: 3
  materials:
    Steel: 400
    Plastic: 200

- type: latheRecipe
  abstract: true
  id: BaseDrinkFlask
  completetime: 0.8
  materials:
    Glass: 200
    
- type: latheRecipe
  abstract: true
  id: Base小utlery
  completetime: 0.8
  materials:
    Steel: 100


# Recipes

- type: latheRecipe
  parent: BaseDrinkFlask
  id: DrinkFlaskBar
  result: DrinkFlaskBar

- type: latheRecipe
  parent: BaseDrinkFlask
  id: DrinkVacuumFlask
  result: DrinkVacuumFlask

- type: latheRecipe
  parent: BaseDrinkShaker
  id: DrinkIceBucket
  result: DrinkIceBucket

- type: latheRecipe
  parent: BaseDrinkShaker
  id: DrinkShaker
  result: DrinkShaker

- type: latheRecipe
  parent: DrinkMugMetal
  id: DrinkJigger
  result: DrinkJigger

- type: latheRecipe
  parent: Base小utlery
  id: Spoon
  result: Spoon

- type: latheRecipe
  parent: Base小utlery
  id: Fork
  result: Fork

- type: latheRecipe
  parent: Base小utlery
  id: BarSpoon
  result: BarSpoon
  materials:
    Steel: 200

- type: latheRecipe
  parent: FoodPlatePlastic
  id: Urn
  result: Urn


- type: latheRecipe
  id: ADTAdvancedReagentGrinderMachineCircuitboard
  result: ADTAdvancedReagentGrinderMachineCircuitboard
  completetime: 2
  materials:
    Glass: 1000
    Steel: 500
    Gold: 500

- type: latheRecipe
  id: BoxFolderRed
  result: BoxFolderRed
  completetime: 3
  materials:
    Cardboard: 300

- type: latheRecipe
  id: BoxFolderBlue
  result: BoxFolderBlue
  completetime: 3
  materials:
    Cardboard: 300

- type: latheRecipe
  id: BoxFolderYellow
  result: BoxFolderYellow
  completetime: 3
  materials:
    Cardboard: 300

- type: latheRecipe
  id: BoxFolderWhite
  result: BoxFolderWhite
  completetime: 3
  materials:
    Cardboard: 300

- type: latheRecipe
  id: BoxFolderGrey
  result: BoxFolderGrey
  completetime: 3
  materials:
    Cardboard: 300

- type: latheRecipe
  id: BoxFolderBlack
  result: BoxFolderBlack
  completetime: 3
  materials:
    Cardboard: 300

- type: latheRecipe
  id: BoxFolderGreen
  result: BoxFolderGreen
  completetime: 3
  materials:
    Cardboard: 300

- type: latheRecipe
  id: ADTWeaponLauncherHydra
  result: WeaponLauncherHydra
  completetime: 3
  materials:
    Steel: 3500
    Gold: 500
    Plastic: 1000
    Glass: 2000

- type: latheRecipe
  id: GrenadeCleanade
  result: GrenadeCleanade
  completetime: 0.5
  materials:
    Steel: 200
    Gold: 300
    Plastic: 100
