- type: job
  id: ADTSeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobADTSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 6h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 60h
  weight: 9
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    id: SeniorEngineerPDA
    ears: ClothingHeadsetEngineering
    pocket1: PowerDrill

- type: chameleonOutfit
  id: ADTSeniorEngineerChameleonOutfit
  job: ADTSeniorEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
