- type: job
  id: ADTSeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobADTSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 216000 # 60 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    id: SeniorEngineerPDA
    ears: ClothingHeadsetEngineering
    pocket1: PowerDrill
