- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Chaplain  # ADT Chaplain
      statusIcon: ChaplainFaction
    #- type: BibleUser #Lets them heal with bibles


- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    # id: ChaplainPDA ADT: different PDAs in loadouts
    ears: ClothingHeadsetService
  storage:
    back:
    - Bible
    - RubberStampChaplain
    - ADTEctoSword  # ADT Phantom
