- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9000 # 2.5 hrs
    #ADT tweak start
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Vox
      #ADT tweak end
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    # shoes: ClothingShoesBootsLaceup ADT-Tweak
    # id: LawyerPDA ADT: different PDAs in loadouts
    ears: ClothingHeadsetLawyer
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - ADTBookSpaceLaw #ADT-WikiBooks
