- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 hrs Ganimed-RoleTime
#  - !type:DepartmentTimeRequirement
#    department: Security
#    time: 18000 #5 hrs Ganimed-RoleTime
    #ADT tweak start
    #- !type:SpeciesRequirement
    #  inverted: true
    #  species:
    #  - Vox
    #ADT tweak end
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-magistrat #Ganimed-Tweak
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    # id: LawyerPDA ADT: different PDAs in loadouts
    ears: ClothingHeadsetLawyer
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - ADTBookSpaceLaw #ADT-WikiBooks
