# Оригинал данного прототипа был сделан @temporaldarkness (discord). Прототип был взят с https://github.com/ss14-ganimed/ENT14-Master.
# Ganimed-Proto-Start

- type: entity
  id: ADTCrateServicePrinterInkCartridge
  parent: CratePlastic
  components:
  - type: StorageFill
    contents:
      - id: ADTBookPrinterInkCartridge

# Ganimed-Proto-End

- type: entity
  id: ADTCrateFishingGoodies
  parent: CratePlastic
  name: fishing goodies crate
  description: A couple of fishing rods, a bear, and a hat. Everything you need to catch all fish on the station!
  components:
  - type: StorageFill
    contents:
      - id: ADTFishingRod
      - id: ADTFishingRodGoon
      - id: ClothingHeadFishCap
      - id: ADTDrinkBeerCanPack

- type: entity
  id: CrateSlotMachine
  parent: CrateGenericSteel
  name: slot machine crate
  description: A crate with a slot machine inside, Everythng you need to start your own gambling addiction!
  components:
  - type: StorageFill
    contents:
      - id: SlotMachineFlatpack