- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requireAdminNotify: true # Ganimed Rules Tweak
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 21600 #6 hrs #Ganimed-RoleTime
  - !type:DepartmentTimeRequirement
    department: Science
    time: 72000 #20 hrs Ganimed-RoleTime
  - !type:OverallPlaytimeRequirement
    time: 144000 #40 hrs Ganimed-RoleTime
  - !type:AgeRequirement # Ganimed-MRP
    requiredAge: 21
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: true # Ganimed-MRP
  antagAdvantage: 5 # Ganimed-MRP: Heads can be antags
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
#  - !type:AddImplantSpecial # Ganimed-MRP
#    implants: [ MindShieldImplant ] # Ganimed-MRP
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: ResearchDirectorGear
  # equipment: # ADT tweak
 #id: RnDPDA # ADT Tweak
    # ears: ClothingHeadsetRD # ADT tweak
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadoutStart
    # - ADTHumanCubeWrapped #ADT-CustomADTLoadoutEnd # Ganimed-Remove

- type: chameleonOutfit
  id: ResearchDirectorChameleonOutfit
  job: ResearchDirector
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretRND
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckCloakRd
    outerClothing: ClothingOuterCoatRD
    gloves: ClothingHandsGlovesColorPurple
