- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 18000 #5 hrs
  - !type:DepartmentTimeRequirement
    department: Science
    time: 36000 #10 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # - type: PhantomTyranyTarget # ADT Phantom

- type: startingGear
  id: ResearchDirectorGear
  # equipment: # ADT tweak
 #id: RnDPDA # ADT Tweak
    # ears: ClothingHeadsetRD # ADT tweak
  storage:
    back:
    - Flash
    - ADTtelescopicBaton #ADT-CustomADTLoadout
