- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 15h # Corvax-RoleTime 5
  - !type:DepartmentTimeRequirement
    department: Security
    time: 5h # Corvax-RoleTime
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 15h # Corvax-RoleTime 5
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 10h # Corvax-RoleTime 3
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10h # Corvax-RoleTime
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 30h # Corvax-RoleTime 5
  - !type:DepartmentTimeRequirement
    department: Security
    time: 15h # Corvax-RoleTime 5
  # should be changed to nukie playtime when thats tracked (wyci)
  guides: [ NuclearOperatives ]

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ADTClothingModsuitBackSyndicate #ADT tweak
    # mask: ClothingMaskGasSyndicate ADT tweak
    # eyes: ClothingEyesHudSyndicate ADT tweak
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    # outerClothing: ClothingOuterHardsuitSyndie ADT tweak
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiOperativePDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: PlushieCarp
    belt: ClothingBeltAssault #ADT nukebuff
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio40TC

- type: chameleonOutfit
  id: NukeopsOutfit
  name: roles-antag-nuclear-operative-name
  startingGear: SyndicateOperativeGearFullNoUplink
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndie
    neck: ClothingNeckScarfStripedSyndieRed

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    id: SyndiCommanderPDA
    eyes: ClothingEyesHudSyndicate #ADT tweak
    back: ADTClothingModsuitBackSyndicateCommander #ADT tweak
    neck: SyndicateWhistle
    # outerClothing: ClothingOuterHardsuitSyndieCommander #ADT tweak
  inhand:
  - NukeOpsDeclarationOfWar
# ADT-NukieCommanderGear-tweak-start (если вписать тупо последнее, то остальное не заспавнится)
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter
    - ADTHandheldShuttleConsoleSyndicate
    - ADTSyndiMechUplink
# ADT-NukieCommanderGear-tweak-end

- type: chameleonOutfit
  id: NukeopsCommanderOutfit
  name: roles-antag-nuclear-operative-commander-name
  startingGear: SyndicateCommanderGearFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieCommander
    neck: ClothingNeckScarfStripedSyndieGreen

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    back: ADTClothingModsuitBackSyndicateElite #ADT tweak
    eyes: ClothingEyesHudSyndicateAgent
    # outerClothing: ClothingOuterHardsuitSyndieMedic #ADT tweak
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiCorpsmanPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - SyndiHypo
    - SawAdvanced
    - Cautery
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - HandheldHealthAnalyzer
    - CombatMedipen
    - DeathAcidifierImplanter

- type: chameleonOutfit
  id: NukeopsMedicOutfit
  name: roles-antag-nuclear-operative-agent-name
  startingGear: SyndicateOperativeMedicFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieMedic
    neck: ClothingNeckScarfStripedLightBlue

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: BaseUplinkRadio60TC
