## Static

- type: latheRecipePack
  id: ServiceStatic
  recipes:
  #ADT-Tweak-Start
  - ADTWateringCan 
  - Mousetrap
  - ADTPlantAnalyzer
  - ADTBotanicalSeedDNADisk
  #ADT-Tweak-End
  - Bucket
  - Ashtray
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - SprayBottle
  - TrashBag
  - LightReplacer
  - MopItem
  - Holoprojector
  - WetFloorSign
  - WireBrush

- type: latheRecipePack
  id: ServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - UniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - PrinterDocMachineCircuitboard # Corvax-Printer
  - ADTCoffeeMachineCircuitboard # ADT Tweak

## Dynamic

- type: latheRecipePack
  id: Janitor
  recipes:
  - AdvMopItem
  - WeaponSprayNozzle
  - ClothingBackpackWaterTank
  - MegaSprayBottle
  - ADTBluespaceTrashCan # ADT tweak
  - ADTAdvancedWateringCan #ADT-Tweak

- type: latheRecipePack
  id: Instruments
  recipes:
  - SynthesizerInstrument
  - PushHorn

- type: latheRecipePack
  id: ServiceBoards
  recipes:
  - ADTElectricRangeMachineCircuitBoard #ADT Tweak
  - ADTKitchenAssemblerMachineCircuitBoard #ADT Tweak
  - BiofabricatorMachineCircuitboard
  - FatExtractorMachineCircuitboard
  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
  - SeedExtractorMachineCircuitboard # ^
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
  # ADT-Tweak-Start
  - ADTAdvancedMicrowaveMachineCircuitBoard
  - ADTCoffeeMachineBluespaceCircuitboard
  - ADTAdvancedReagentGrinderMachineCircuitboard
  - ADTHydroponicsTrayAdvancedMachineCircuitboard
  # ADT-Tweak-End
