## Static

- type: latheRecipePack
  id: ServiceStatic
  recipes:
  - Mousetrap  # ADT Tweak
  - TrashBag  # ADT Tweak
  - ADTPlantAnalyzer # ADT Tweak
  - Bucket
  - Ashtray
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - SprayBottle
  - LightReplacer
  - MopItem
  - Holoprojector
  - WetFloorSign

- type: latheRecipePack
  id: ServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - UniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - PrinterDocMachineCircuitboard # Corvax-Printer
  - ADTCoffeeMachineCircuitboard # ADT Tweak

## Dynamic

- type: latheRecipePack
  id: Janitor
  recipes:
  - AdvMopItem
  - WeaponSprayNozzle
  - ClothingBackpackWaterTank
  - MegaSprayBottle
  - ADTBluespaceTrashCan # ADT tweak

- type: latheRecipePack
  id: Instruments
  recipes:
  - SynthesizerInstrument
  - PushHorn

- type: latheRecipePack
  id: ServiceBoards
  recipes:
  - ADTElectricRangeMachineCircuitBoard #ADT Tweak
  - ADTKitchenAssemblerMachineCircuitBoard #ADT Tweak
  - BiofabricatorMachineCircuitboard
  - FatExtractorMachineCircuitboard
  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
  - SeedExtractorMachineCircuitboard # ^
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
  - CloningPodMachineCircuitboard #ADT tweak
  - CloningConsoleComputerCircuitboard #ADT tweak
  - MedicalScannerMachineCircuitboard #ADT tweak
  - ADTAdvancedMicrowaveMachineCircuitBoard #ADT tweak
  - ADTCoffeeMachineBluespaceCircuitboard #ADT tweak
  - ADTAdvancedReagentGrinderMachineCircuitboard #ADT tweak
  - ADTHydroponicsTrayAdvancedMachineCircuitboard #ADT tweak
